/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        INPUT_CATEGORY: 'INPUT',
        INFRARED_VALUE: 'read line follower pin %1',
        INFRARED_VALUE1: 'read line follower pin %1',
        IR_L1: 'Leftport1',
        IR_R1: 'Rightport1',
        IR_L2: 'Leftport2',
        IR_R2: 'Rightport2',
        IR_L3: 'Leftport3',
        IR_R3: 'Rightport3',
        IR_L4: 'Leftport4',
        IR_R4: 'Rightport4',
        IR_L5: 'Leftport5',
        IR_R5: 'Rightport5',
        IR_L6: 'Leftport6',
        IR_R6: 'Rightport6',
        IR_L7: 'Leftport7',
        IR_R7: 'Rightport7',
        IR_L8: 'Leftport8',
        IR_R8: 'Rightport8',
        SOUND_VALUE: 'read voice pin %1',
		portsAD1: 'PORT1',
		portsAD2: 'PORT2',
		portsAD3: 'PORT3',
		portsAD4: 'PORT4',
		portsAD5: 'PORT5',
		portsAD6: 'PORT6',
		portsAD7: 'PORT7',
		portsAD8: 'PORT8',
		LIGHTSENSOR_VALUE:  'read Button sensor pin %1',
		BUTTON_VALUE:  'button %1',
		PO1:  'port1',
		PO2:  'port2',
		PO3:  'port3',
		PO4:  'port4',
		PO5:  'port5',
		PO7:  'port7',
		PO6:  'port6',
		PO8:  'port8',
        GRAY_VALUE: 'read Grayscale sensor %1 at LED %2',
		LEDON:  'on',
		LEDOFF:  'off',
		PIR_VALUE:  'read PIR %1',
		ULTRASONIC_INIT:  'init ultrasonic sensor TRIG %1 ECHO %2',
		tport1:  'tPort1',
		tport2:  'tPort2',
		tport3:  'tPort3',
		tport4:  'tPort4',
		tport5:  'tPort5',
		tport6:  'tPort6',
		tport7:  'tPort7',
		tport8:  'tPort8',
		eport1:  'ePort1',
		eport2:  'ePort2',
		eport3:  'ePort3',
		eport4:  'ePort4',
		eport5:  'ePort5',
		eport6:  'ePort6',
		eport7:  'ePort7',
		eport8:  'ePort8',
		ULTRASONIC_VALUE:  '%1 get distance',
		SHT_VALUE:  'Identify %1 Humiture sensor %2',
		Temp:  'Temperature',
		Hum:  'Humidity',
		GYRO_VALUE:  'Identify %1 GYRO %2',
		gyro_x:  'x',
		gyro_y:  'y',
		gyro_z:  'z',
		GYRO_VALUE2:  'Identify %1 GYRO %2 ',
		GYRO_VALUE3:  'Read %1 yaw ',
		front:  'front',
		back:  'back',
		right:  'right',
		left:  'left',
		COLOR_VALUE:  'Identify color %1',
		COLOR_VALUE2:  ' %1 Identifycolor %2 value',
		COLOR_VALUE3:  'Identify color %1 value',
		red:  'red',
		green:  'green',
		blue:  'blue',
		yellow:  'yellow'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        INPUT_CATEGORY: '输入类',
        INFRARED_VALUE: '巡线传感器 %1',
        INFRARED_VALUE1: '巡线传感器 %1',
        IR_L1: '接口1左',
        IR_R1: '接口1右',
        IR_L2: '接口2左',
        IR_R2: '接口2右',
        IR_L3: '接口3左',
        IR_R3: '接口3右',
        IR_L4: '接口4左',
        IR_R4: '接口4右',
        IR_L5: '接口5左',
        IR_R5: '接口5右',
        IR_L6: '接口6左',
        IR_R6: '接口6右',
        IR_L7: '接口7左',
        IR_R7: '接口7右',
        IR_L8: '接口8左',
        IR_R8: '接口8右',
        SOUND_VALUE: '声音传感器 %1',
		portsAD1: '接口1',
		portsAD2: '接口2',
		portsAD3: '接口3',
		portsAD4: '接口4',
		portsAD5: '接口5',
		portsAD6: '接口6',
		portsAD7: '接口7',
		portsAD8: '接口8',
		LIGHTSENSOR_VALUE:  '光敏传感器 %1',
		BUTTON_VALUE:  '按钮开关 %1',
		PO1:  '端口1',
		PO2:  '端口2',
		PO3:  '端口3',
		PO4:  '端口4',
		PO5:  '端口5',
		PO7:  '端口7',
		PO6:  '端口6',
		PO8:  '端口8',
        GRAY_VALUE: '灰度传感器 %1 %2 灯',
		LEDON:  '开',
		LEDOFF:  '关',
		PIR_VALUE:  '人体感应 %1',
		ULTRASONIC_INIT:  '超声波TRIG %1 ECHO %2',
		tport1:  '端口1',
		tport2:  '端口2',
		tport3:  '端口3',
		tport4:  '端口4',
		tport5:  '端口5',
		tport6:  '端口6',
		tport7:  '端口7',
		tport8:  '端口8',
		eport1:  '端口1',
		eport2:  '端口2',
		eport3:  '端口3',
		eport4:  '端口4',
		eport5:  '端口5',
		eport6:  '端口6',
		eport7:  '端口7',
		eport8:  '端口8',
		ULTRASONIC_VALUE:  '超声波 %1 距离',
		SHT_VALUE:  '温湿度传感器 %1 检测到 %2',
		Temp:  '温度',
		Hum:  '湿度',
		GYRO_VALUE:  '陀螺仪 %1 %2 角度',
		gyro_x:  'x轴',
		gyro_y:  'y轴',
		gyro_z:  'z轴',
		GYRO_VALUE2:  '陀螺仪 %1 检测到 %2',
		GYRO_VALUE3:  '陀螺仪 %1 偏航角',
		front:  '向前',
		back:  '向后',
		right:  '向右',
		left:  '向左',
		COLOR_VALUE:  '颜色传感器(端口5/端口7)检测到 %1',
		COLOR_VALUE2:  ' %1 颜色传感器 %2 值',
		COLOR_VALUE3:  '颜色传感器端口7 %1 值',
		red:  '红色',
		green:  '绿色',
		blue:  '蓝色',
		yellow:  '黄色'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
		INPUT_CATEGORY: '입력 카테고리',
		INFRARED_VALUE: '라인 추적 센서 %1',
		INFRARED_VALUE1: '라인 추적 센서 %1',
		IR_L1: '인터페이스 1 남음',
		IR_R1: '인터페이스 1 오른쪽',
		IR_L2: '인터페이스 2 왼쪽',
		IR_R2: '인터페이스 2 오른쪽',
		IR_L3: '인터페이스 3 남음',
		IR_R3: '인터페이스 3 오른쪽',
		IR_L4: '인터페이스 4 왼쪽',
		IR_R4: '인터페이스 4 오른쪽',
		IR_L5: '인터페이스 5 남음',
		IR_R5: '인터페이스 5 오른쪽',
		IR_L6: '인터페이스 6 왼쪽',
		IR_R6: '인터페이스 6 오른쪽',
		IR_L7: '인터페이스 7 남음',
		IR_R7: '인터페이스 7 오른쪽',
		IR_L8: '인터페이스 8 왼쪽',
		IR_R8: '인터페이스 8 오른쪽',
		SOUND_VALUE: '소리 센서 %1',
		portsAD1: '인터페이스 1',
		portsAD2: '인터페이스 2',
		portsAD3: '인터페이스 3',
		portsAD4: '인터페이스 4',
		portsAD5: '인터페이스 5',
		portsAD6: '인터페이스 6',
		portsAD7: '인터페이스 7',
		portsAD8: '인터페이스 8',
		LIGHTSENSOR_VALUE: '조도 센서 %1',
		BUTTON_VALUE: '버튼 스위치 %1',
		PO1: '포트 1',
		PO2: '포트 2',
		PO3: '포트 3',
		PO4: '포트 4',
		PO5: '포트 5',
		PO7: '포트 7',
		PO6: '포트 6',
		PO8: '포트 8',
		GRAY_VALUE: '회색 센서 %1 %2 조명',
		LEDON: '켜짐',
		LEDOFF: '끄기',
		PIR_VALUE: '개인 감지 %1',
		ULTRASONIC_INIT: '초음파 TRIG %1 에코 %2',
		tport1: '포트 1',
		tport2: '포트 2',
		tport3: '포트 3',
		tport4: '포트 4',
		tport5: '포트 5',
		tport6: '포트 6',
		tport7: '포트 7',
		tport8: '포트 8',
		eport1: '포트 1',
		eport2: '포트 2',
		eport3: '포트 3',
		eport4: '포트 4',
		eport5: '포트 5',
		eport6: '포트 6',
		eport7: '포트 7',
		eport8: '포트 8',
		ULTRASONIC_VALUE: '초음파 %1 거리',
		SHT_VALUE: '온도 및 습도 센서 %1 가 %2 을(를) 감지했습니다.',
		Temp: '온도',
		Hum: '습도',
		GYRO_VALUE: '자이로스코프 %1 %2 각도',
		gyro_x: 'x축',
		gyro_y: 'y축',
		gyro_z: 'z축',
		GYRO_VALUE2: '자이로스코프 %1 가 %2 감지됨',
		GYRO_VALUE3: '자이로스코프 %1 요 각도',
		front: '앞으로',
		back: '뒤로',
		right: '오른쪽으로',
		left: '왼쪽으로',
		COLOR_VALUE: '컬러 센서(포트 5/포트 7)가 %1 감지됨',
		COLOR_VALUE2: '%1 컬러 센서 %2 값',
		COLOR_VALUE3: '컬러 센서 포트 7 %1 값',
		red: '빨간색',
		green: '녹색',
		blue: '파란색',
		yellow: '노란색'
    });
    return Blockly;
}

exports = addMsg;
