/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        OUTPUTTFT_CATEGORY: 'OUTPUT',
        OUTPUTTFT_MOTOR: 'Set %1 direction %2 speed（0~255）%3',
        OUTPUTTFT_MOTOR2: 'Set %1 direction %2',
        OUTPUTTFT_MOTOR_M1: 'M1',
        OUTPUTTFT_MOTOR_M2: 'M2',
        OUTPUTTFT_MOTOR_M3: 'M3',
        OUTPUTTFT_MOTOR_M4: 'M4',
        OUTPUTTFT_MOTOR_M6: 'M6',
		OUTPUTTFT_MOTOR_foreward:  'foreward',
		OUTPUTTFT_MOTOR_reversal:  'reversal',
		OUTPUTTFT_MOTOR_stop:  'stop',
		D5R:  'port5 LED1',
		D5Y:  'port5 LED2',
		D5G:  'port5 LED3',
		D7R:  'port7 LED1',
		D7Y:  'port7 LED2',
		D7G:  'port7 LED3',
		D8R:  'port8 LED1',
		D8Y:  'port8 LED2',
		D8G:  'port8 LED3',
		D5R2:  'port5 RED',
		D5Y2:  'port5 YELLOW',
		D5G2:  'port5 GREEN',
		D7R2:  'port7 RED',
		D7Y2:  'port7 YELLOW',
		D7G2:  'port7 GREEN',
		D8R2:  'port8 RED',
		D8Y2:  'port8 YELLOW',
		D8G2:  'port8 GREEN',
		ON:  'ON',
		OFF:  'OFF',
        OUTPUTTFT_LED: 'Set LED %1 as %2 ',
        OUTPUTTFT_LED2: 'Set LED %1 as %2 ',
		PO1:  'port1',
		PO2:  'port2',
		PO3:  'port3',
		PO4:  'port4',
		PO5:  'port5',
		PO6:  'port6',
		PO7:  'port7',
		PO8:  'port8',
        OUTPUTTFT_BUZZER: 'Set BUZZER %1 as %2 ',
		Half:  'Half',
		Quarter:  'Quarter',
		Eighth:  'Eighth',
		Whole:  'Whole',
		Double:  'Double',
		Zero:  'Zero',
        OUTPUTTFT_BUZZER2: 'play tone pin %1 on note %2 beat %3',
        OUTPUTTFT_SERVO: 'et 180° servo pin  %1 as %2',
        OUTPUTTFT_SERVO2: 'et 270° servo pin  %1 as %2',
		OUTPUTTFT_STRING: 'Show string %1 ',
		OUTPUTTFT_STRING2: 'Show string %1 value %2 ',
		OUTPUTTFT_SMILE: 'Show emoticons %1 ',
		aixin1: 'Love',
		dui: 'Yes',
		cuo: 'Wrong',
		xiaolian: 'Smiling',
		kulian: 'Crying',
		wubiaoqing: 'No expression',
		jingya: 'Surprised',
		shangxin: 'Sad',
		tushetou: 'Spit your tongue',
		jiandao: 'Scissors',
		shitou: 'Stone',
		bu: 'Cloth',
        TFT_SETWIFI: 'set WIFI ssid %1 password %2',
        TFT_USEWIFI: 'Using wireless updates',
        OUTPUTTFT_MAKEDIS: 'set 7-segments display %1 number %2',
        OUTPUTTFT_MAKEDIS2: 'set 7-segments display %1 number %2 to %3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        OUTPUTTFT_CATEGORY: '输出类',
        OUTPUTTFT_MOTOR: '设置 %1 方向 %2 速度（0~255）%3',
        OUTPUTTFT_MOTOR2: '设置 %1 方向 %2',
        OUTPUTTFT_MOTOR_M1: '电机1',
        OUTPUTTFT_MOTOR_M2: '电机2',
        OUTPUTTFT_MOTOR_M3: '电机3',
        OUTPUTTFT_MOTOR_M4: '电机4',
        OUTPUTTFT_MOTOR_M6: '电机6',
		OUTPUTTFT_MOTOR_foreward:  '正转',
		OUTPUTTFT_MOTOR_reversal:  '反转',
		OUTPUTTFT_MOTOR_stop:  '停止',
		D5R:  '端口5 LED1',
		D5Y:  '端口5 LED2',
		D5G:  '端口5 LED3',
		D7R:  '端口7 LED1',
		D7Y:  '端口7 LED2',
		D7G:  '端口7 LED3',
		D8R:  '端口8 LED1',
		D8Y:  '端口8 LED2',
		D8G:  '端口8 LED3',
		D5R2:  '端口5 红灯',
		D5Y2:  '端口5 黄灯',
		D5G2:  '端口5 绿灯',
		D7R2:  '端口7 红灯',
		D7Y2:  '端口7 黄灯',
		D7G2:  '端口7 绿灯',
		D8R2:  '端口8 红灯',
		D8Y2:  '端口8 黄灯',
		D8G2:  '端口8 绿灯',
		ON:  '开',
		OFF:  '关',
        OUTPUTTFT_LED: '设置LED灯 %1 为 %2 ',
        OUTPUTTFT_LED2: '设置LED灯 %1 为 %2 ',
		PO1:  '端口1',
		PO2:  '端口2',
		PO3:  '端口3',
		PO4:  '端口4',
		PO5:  '端口5',
		PO6:  '端口6',
		PO7:  '端口7',
		PO8:  '端口8',
        OUTPUTTFT_BUZZER: '设置蜂鸣器 %1 为 %2 ',
		Half:  '二分之一',
		Quarter:  '四分之一',
		Eighth:  '八分之一',
		Whole:  '整拍',
		Double:  '双拍',
		Zero:  '停止',
        OUTPUTTFT_BUZZER2: '播放引脚 %1 音调为 %2 节拍为 %3',
        OUTPUTTFT_SERVO: '设置180°舵机 %1 角度 %2',
        OUTPUTTFT_SERVO2: '设置270°舵机 %1 角度 %2',
		OUTPUTTFT_STRING: '显示字符串 %1 ',
		OUTPUTTFT_STRING2: '显示字符串 %1 值 %2 ',
		OUTPUTTFT_SMILE: '显示表情 %1 ',
		aixin1: '爱心',
		dui: '对',
		cuo: '错',
		xiaolian: '笑脸',
		kulian: '哭脸',
		wubiaoqing: '无表情',
		jingya: '惊讶',
		shangxin: '伤心',
		tushetou: '吐舌头',
		jiandao: '剪刀',
		shitou: '石头',
		bu: '布',
        TFT_SETWIFI: '设置 WIFI 账号%1 密码 %2',
        TFT_USEWIFI: '使用无线更新',
        OUTPUTTFT_MAKEDIS: '设置数码管 %1 数字 %2',
        OUTPUTTFT_MAKEDIS2: '设置数码管 %1 显示 %2 比 %3'
    });
    Object.assign(Blockly.ScratchMsgs.locales['ko'], {
		OUTPUTTFT_CATEGORY: '출력 카테고리',
		OUTPUTTFT_MOTOR: '%1 방향 %2 속도 설정(0~255)%3',
		OUTPUTTFT_MOTOR2: '%1 방향 %2 설정',
		OUTPUTTFT_MOTOR_M1: '모터 1',
		OUTPUTTFT_MOTOR_M2: '모터 2',
		OUTPUTTFT_MOTOR_M3: '모터 3',
		OUTPUTTFT_MOTOR_M4: '모터 4',
		OUTPUTTFT_MOTOR_M6: '모터 6',
		OUTPUTTFT_MOTOR_foreward: '앞으로',
		OUTPUTTFT_MOTOR_reversal: '반전',
		OUTPUTTFT_MOTOR_stop: '중지',
		D7R: '포트 7 LED1',
		D7Y: '포트 7 LED2',
		D7G: '포트 7 LED3',
		D8R: '포트 8 LED1',
		D8Y: '포트 8 LED2',
		D8G: '포트 8 LED3',
		D7R2: '포트 7 빨간색 표시등',
		D7Y2: '포트 7 노란색 표시등',
		D7G2: '포트 7 녹색 표시등',
		D8R2: '포트 8 빨간색 표시등',
		D8Y2: '포트 8 노란색 표시등',
		D8G2: '포트 8 녹색 표시등',
		ON: '열기',
		OFF: '끄기',
		OUTPUTTFT_LED: 'LED %1을(를) %2로 설정',
		OUTPUTTFT_LED2: 'LED %1을(를) %2로 설정',
		PO1: '포트 1',
		PO2: '포트 2',
		PO3: '포트 3',
		PO4: '포트 4',
		PO5: '포트 5',
		PO6: '포트 6',
		PO7: '포트 7',
		PO8: '포트 8',
		OUTPUTTFT_BUZZER: '부저 %1을(를) %2에 설정',
		Half: '1/2',
		Quarter: '분기',
		Eighth: '8분의 1',
		Whole: '전체 비트',
		Double: '더블샷',
		Zero: '그만해',
		OUTPUTTFT_BUZZER2: '%1 핀을 %2 피치, 비트 %3으로 재생 중',
		OUTPUTTFT_SERVO: '%1 각도 %2 서보 설정 180°',
		OUTPUTTFT_SERVO2: '%1 각도 %2 서보 설정 270°',
		OUTPUTTFT_STRING: '표시 문자열 %1',
		OUTPUTTFT_STRING2: '표시 문자열 %1 설정 %2 ',
		OUTPUTTFT_SMILE: '이모티콘 %1 표시',
		aixin1: '사랑',
		dui: '맞아',
		cuo: '틀렸어',
		xiaolian: '웃는 얼굴',
		kulian: '우는 얼굴',
		wubiaoqing: '표현 없음',
		jingya: '놀랐어요',
		shangxin: '슬프다',
		tushetou: '혀를 내밀어',
		jandao: '가위',
		Shitou: '돌',
		bu: '천',
        TFT_SETWIFI: 'WIFI 계정 %1 비밀번호 %2 설정',
        TFT_USEWIFI: '무선 업데이트 사용',
		OUTPUTTFT_MAKEDIS: '닉시 튜브 %1 자리 %2 설정',
		OUTPUTTFT_MAKEDIS2: '유닛 튜브 %1을(를) %2를 %3까지 표시하도록 설정'
    });
    return Blockly;
}

exports = addMsg;